import sqlite3

## Connect to sqllite
connection = sqlite3.connect("student.db")

## Create a cursor object to inser, create, retrive table
cursor = connection.cursor()

#create a table
table_info = """
Create table STUDENT(NAME VARCHAR(25), CLASS VARCHAR(25),
SECTION VARCHAR(25), MARKS INT);
"""
cursor.execute(table_info)

##Insert some more records


cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'B', 66)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Technician', 'F', 54)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'DEVOPS', 'D', 88)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Technician', 'S', 59)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Web Development', 'S', 71)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Science', 'C', 65)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Technician', 'B', 97)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Science', 'S', 72)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Analyst', 'S', 79)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Science', 'S', 77)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'S', 99)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Technician', 'S', 82)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'B', 89)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'A', 63)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Web Development', 'F', 76)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Science', 'C', 57)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Analyst', 'F', 94)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Analyst', 'C', 86)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'D', 94)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Analyst', 'C', 85)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'AI', 'F', 65)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'D', 96)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'DEVOPS', 'C', 84)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Science', 'S', 72)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'DEVOPS', 'S', 75)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Technician', 'S', 80)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Data Science', 'B', 80)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'F', 93)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Analyst', 'D', 74)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'B', 50)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Technician', 'B', 96)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'B', 58)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'F', 90)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'AI', 'B', 81)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'F', 55)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Analyst', 'C', 97)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Web Development', 'F', 70)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Machine Learning', 'C', 66)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Machine Learning', 'S', 67)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'A', 80)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'DEVOPS', 'B', 63)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'DEVOPS', 'A', 56)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'S', 68)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Science', 'B', 97)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Data Analyst', 'B', 53)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Web Development', 'A', 64)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Technician', 'B', 78)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'B', 73)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'DEVOPS', 'S', 54)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Analyst', 'B', 66)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'A', 78)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Science', 'B', 89)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Machine Learning', 'D', 74)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Machine Learning', 'S', 66)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Science', 'D', 93)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'D', 93)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'C', 57)''')
cursor.execute('''Insert Into STUDENT values('David', 'Technician', 'D', 93)''')
cursor.execute('''Insert Into STUDENT values('David', 'DEVOPS', 'S', 70)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Technician', 'A', 72)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'DEVOPS', 'B', 55)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Analyst', 'D', 98)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'DEVOPS', 'S', 78)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'S', 88)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Science', 'C', 94)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'B', 66)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Machine Learning', 'B', 82)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'DEVOPS', 'D', 89)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Technician', 'C', 66)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Technician', 'A', 89)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Science', 'B', 83)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Data Analyst', 'C', 53)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Machine Learning', 'F', 53)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'B', 86)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Machine Learning', 'F', 70)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'AI', 'D', 85)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Science', 'F', 85)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Science', 'A', 89)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Analyst', 'C', 58)''')
cursor.execute('''Insert Into STUDENT values('David', 'DEVOPS', 'S', 80)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'DEVOPS', 'C', 90)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Analyst', 'B', 75)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'B', 93)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Web Development', 'D', 70)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'DEVOPS', 'C', 57)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Analyst', 'C', 54)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'B', 54)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'A', 81)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Machine Learning', 'C', 76)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Science', 'B', 87)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'S', 63)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Science', 'C', 92)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'S', 70)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Machine Learning', 'A', 90)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Analyst', 'B', 93)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Web Development', 'A', 81)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Web Development', 'C', 74)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Web Development', 'F', 84)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Machine Learning', 'S', 93)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Web Development', 'D', 74)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Science', 'C', 72)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Science', 'D', 68)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'F', 86)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'C', 93)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'F', 74)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Machine Learning', 'A', 69)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'F', 68)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Web Development', 'A', 75)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Technician', 'F', 99)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Technician', 'F', 63)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'DEVOPS', 'B', 66)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Data Science', 'B', 81)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'AI', 'S', 75)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'AI', 'B', 92)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Web Development', 'S', 92)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'DEVOPS', 'S', 97)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'AI', 'S', 66)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Technician', 'A', 70)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Machine Learning', 'S', 82)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Web Development', 'D', 76)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Machine Learning', 'B', 69)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'C', 82)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'AI', 'C', 89)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'D', 52)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Technician', 'A', 96)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Analyst', 'D', 78)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'AI', 'D', 58)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'S', 85)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Machine Learning', 'F', 97)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Web Development', 'C', 76)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Technician', 'D', 58)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Machine Learning', 'B', 76)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Science', 'C', 72)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Technician', 'C', 72)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Machine Learning', 'C', 96)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'F', 90)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Science', 'B', 50)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Web Development', 'S', 89)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'A', 86)''')
cursor.execute('''Insert Into STUDENT values('David', 'Technician', 'F', 78)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Machine Learning', 'B', 75)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'AI', 'F', 76)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'DEVOPS', 'A', 54)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Web Development', 'S', 93)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Machine Learning', 'D', 76)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Machine Learning', 'B', 81)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Analyst', 'C', 56)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Technician', 'S', 73)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'D', 87)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Machine Learning', 'F', 58)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'C', 55)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Web Development', 'S', 81)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'B', 64)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'A', 92)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'C', 71)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Machine Learning', 'B', 76)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Technician', 'C', 81)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Analyst', 'A', 61)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'F', 74)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'F', 86)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Science', 'C', 58)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Web Development', 'A', 96)''')
cursor.execute('''Insert Into STUDENT values('David', 'Machine Learning', 'C', 71)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Science', 'S', 74)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Science', 'C', 69)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'DEVOPS', 'F', 93)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Web Development', 'B', 70)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'S', 89)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Technician', 'S', 64)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'C', 89)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Machine Learning', 'C', 69)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'C', 68)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Technician', 'S', 90)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Science', 'D', 96)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'S', 85)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'C', 89)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Science', 'B', 50)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Machine Learning', 'S', 50)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'C', 60)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'AI', 'S', 53)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Machine Learning', 'A', 80)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'AI', 'B', 71)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Web Development', 'A', 98)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Web Development', 'B', 59)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'S', 56)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'AI', 'B', 59)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'C', 61)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'DEVOPS', 'B', 81)''')
cursor.execute('''Insert Into STUDENT values('David', 'Technician', 'D', 78)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Machine Learning', 'B', 98)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Science', 'A', 74)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'D', 55)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'B', 78)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Web Development', 'D', 78)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Data Science', 'A', 61)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Science', 'D', 92)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Web Development', 'B', 57)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Technician', 'S', 62)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Data Science', 'D', 77)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Technician', 'A', 84)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Machine Learning', 'A', 58)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Web Development', 'D', 81)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'A', 83)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Web Development', 'F', 55)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'C', 95)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'AI', 'C', 96)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'C', 60)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Analyst', 'D', 90)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Science', 'C', 63)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'S', 66)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'DEVOPS', 'B', 51)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Science', 'C', 59)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Technician', 'C', 91)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'A', 81)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'A', 66)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'D', 77)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Technician', 'D', 84)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Web Development', 'B', 82)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Science', 'S', 57)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'S', 60)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'DEVOPS', 'A', 54)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Machine Learning', 'B', 52)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Technician', 'C', 85)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Machine Learning', 'D', 71)''')
cursor.execute('''Insert Into STUDENT values('David', 'AI', 'B', 99)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Technician', 'D', 54)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'AI', 'A', 52)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'AI', 'C', 80)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'AI', 'F', 69)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Science', 'F', 80)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'AI', 'A', 94)''')
cursor.execute('''Insert Into STUDENT values('David', 'DEVOPS', 'B', 77)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Web Development', 'C', 57)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Technician', 'S', 85)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'F', 71)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Data Science', 'C', 86)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Web Development', 'S', 64)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Machine Learning', 'D', 57)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'AI', 'F', 53)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Web Development', 'D', 91)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'S', 62)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Machine Learning', 'A', 71)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Web Development', 'S', 63)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'AI', 'A', 70)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Machine Learning', 'S', 58)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Analyst', 'F', 83)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Machine Learning', 'B', 85)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Machine Learning', 'F', 54)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Data Science', 'D', 86)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'F', 72)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Technician', 'S', 83)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'AI', 'A', 61)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'DEVOPS', 'B', 95)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Technician', 'C', 67)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Science', 'A', 67)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Data Science', 'C', 63)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'DEVOPS', 'B', 81)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'C', 77)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'S', 74)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'D', 94)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Science', 'S', 91)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'A', 69)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Web Development', 'S', 76)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'A', 83)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Analyst', 'C', 71)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Web Development', 'C', 54)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Machine Learning', 'A', 58)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'AI', 'B', 76)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Web Development', 'B', 79)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Machine Learning', 'B', 98)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'S', 63)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'DEVOPS', 'B', 69)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'A', 73)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Science', 'D', 74)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Science', 'D', 59)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Machine Learning', 'A', 86)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Technician', 'D', 55)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'DEVOPS', 'S', 76)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Web Development', 'B', 60)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Analyst', 'C', 58)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Science', 'B', 60)''')
cursor.execute('''Insert Into STUDENT values('David', 'AI', 'S', 80)''')
cursor.execute('''Insert Into STUDENT values('David', 'Technician', 'S', 83)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Science', 'C', 79)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Technician', 'S', 75)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'DEVOPS', 'D', 53)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'A', 86)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Technician', 'C', 66)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Science', 'C', 64)''')
cursor.execute('''Insert Into STUDENT values('David', 'Technician', 'S', 78)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Analyst', 'D', 94)''')
cursor.execute('''Insert Into STUDENT values('David', 'AI', 'S', 79)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Analyst', 'C', 81)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Machine Learning', 'S', 54)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Science', 'A', 55)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Science', 'D', 75)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'F', 64)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Analyst', 'C', 54)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Machine Learning', 'B', 52)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'S', 69)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'C', 68)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'DEVOPS', 'F', 93)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Technician', 'A', 85)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Analyst', 'S', 85)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'AI', 'B', 90)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Science', 'A', 87)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Technician', 'D', 50)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'F', 52)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Data Analyst', 'C', 55)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Technician', 'D', 77)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Science', 'S', 91)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'C', 73)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Machine Learning', 'D', 85)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Data Science', 'D', 92)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Technician', 'S', 63)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Web Development', 'S', 54)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Machine Learning', 'C', 51)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Machine Learning', 'S', 67)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'DEVOPS', 'D', 66)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Data Analyst', 'C', 81)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Web Development', 'A', 53)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Machine Learning', 'B', 72)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'DEVOPS', 'A', 95)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Data Analyst', 'S', 89)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'C', 68)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Science', 'F', 63)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Web Development', 'D', 74)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'C', 70)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'AI', 'A', 97)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'S', 53)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'DEVOPS', 'C', 62)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'B', 96)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'B', 68)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'AI', 'F', 96)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Data Science', 'S', 56)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Machine Learning', 'D', 73)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'F', 91)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Web Development', 'F', 94)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Science', 'C', 74)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'DEVOPS', 'S', 78)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Web Development', 'D', 52)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Science', 'S', 52)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'A', 94)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Data Science', 'B', 66)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'D', 58)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Web Development', 'S', 81)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'DEVOPS', 'F', 63)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Science', 'B', 77)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Technician', 'C', 73)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'DEVOPS', 'A', 89)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'F', 57)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Technician', 'S', 78)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Technician', 'B', 64)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Science', 'C', 74)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'DEVOPS', 'A', 62)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'DEVOPS', 'F', 52)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Machine Learning', 'S', 66)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Technician', 'A', 59)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Web Development', 'D', 91)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Analyst', 'C', 63)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Machine Learning', 'A', 64)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'DEVOPS', 'C', 98)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Analyst', 'D', 87)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'DEVOPS', 'B', 79)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Analyst', 'D', 58)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'A', 71)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'F', 79)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'A', 80)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Web Development', 'A', 60)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Machine Learning', 'C', 87)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Data Science', 'D', 93)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'DEVOPS', 'A', 85)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Web Development', 'A', 83)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'A', 94)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Machine Learning', 'B', 61)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Technician', 'A', 55)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Technician', 'F', 60)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Data Analyst', 'S', 99)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Machine Learning', 'F', 73)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Science', 'S', 94)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'AI', 'C', 86)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Machine Learning', 'D', 52)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Web Development', 'A', 61)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'F', 72)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Technician', 'S', 94)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Machine Learning', 'S', 67)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'C', 78)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'S', 97)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'F', 57)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'F', 68)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Technician', 'B', 88)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Machine Learning', 'S', 57)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Science', 'F', 89)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'AI', 'S', 52)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Web Development', 'S', 62)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'DEVOPS', 'C', 81)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Machine Learning', 'C', 71)''')
cursor.execute('''Insert Into STUDENT values('David', 'AI', 'B', 84)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'DEVOPS', 'B', 89)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Data Analyst', 'C', 62)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Science', 'B', 51)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Science', 'A', 93)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'C', 84)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Machine Learning', 'D', 96)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Science', 'C', 96)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Science', 'F', 53)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'S', 81)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'AI', 'C', 90)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Machine Learning', 'B', 63)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'DEVOPS', 'F', 97)''')
cursor.execute('''Insert Into STUDENT values('David', 'DEVOPS', 'C', 96)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Science', 'S', 64)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Technician', 'A', 92)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'S', 91)''')
cursor.execute('''Insert Into STUDENT values('David', 'Data Analyst', 'C', 78)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Technician', 'S', 100)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Technician', 'C', 75)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Web Development', 'F', 65)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Technician', 'D', 71)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Machine Learning', 'D', 68)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'DEVOPS', 'B', 94)''')
cursor.execute('''Insert Into STUDENT values('David', 'Web Development', 'C', 79)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Web Development', 'S', 81)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'S', 71)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'A', 70)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'AI', 'D', 77)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Web Development', 'C', 68)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Data Analyst', 'D', 55)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Data Science', 'F', 88)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Data Science', 'F', 92)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'B', 77)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Data Analyst', 'S', 83)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Analyst', 'C', 87)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'S', 51)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'DEVOPS', 'B', 63)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Web Development', 'C', 66)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Technician', 'A', 96)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Science', 'D', 93)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Data Science', 'S', 69)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Technician', 'A', 86)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Machine Learning', 'B', 98)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Analyst', 'C', 55)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'C', 93)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Technician', 'F', 87)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Technician', 'A', 54)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'AI', 'C', 94)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Analyst', 'C', 55)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Data Analyst', 'F', 53)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Technician', 'D', 100)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'D', 77)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Technician', 'B', 82)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Machine Learning', 'F', 90)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'DEVOPS', 'D', 76)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'DEVOPS', 'F', 97)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Machine Learning', 'D', 74)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Technician', 'F', 98)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Machine Learning', 'A', 86)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Web Development', 'D', 94)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'AI', 'A', 71)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Analyst', 'A', 53)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'AI', 'B', 94)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'Data Science', 'D', 98)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'C', 68)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'A', 67)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Data Science', 'C', 86)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Machine Learning', 'S', 86)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'DEVOPS', 'F', 81)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Machine Learning', 'S', 82)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'Data Science', 'F', 57)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'DEVOPS', 'S', 92)''')
cursor.execute('''Insert Into STUDENT values('Shankhar', 'AI', 'S', 89)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'Web Development', 'D', 82)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'DEVOPS', 'B', 54)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Machine Learning', 'A', 71)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'Web Development', 'F', 52)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Machine Learning', 'S', 56)''')
cursor.execute('''Insert Into STUDENT values('David', 'DEVOPS', 'A', 65)''')
cursor.execute('''Insert Into STUDENT values('Charlie', 'Data Analyst', 'S', 57)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Technician', 'S', 86)''')
cursor.execute('''Insert Into STUDENT values('Isabella', 'Web Development', 'C', 69)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'AI', 'B', 94)''')
cursor.execute('''Insert Into STUDENT values('Henry', 'AI', 'D', 80)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'AI', 'D', 88)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Data Analyst', 'C', 79)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'Data Science', 'A', 97)''')
cursor.execute('''Insert Into STUDENT values('David', 'AI', 'F', 80)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'AI', 'D', 94)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Web Development', 'B', 55)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'DEVOPS', 'B', 66)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'DEVOPS', 'F', 60)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Web Development', 'D', 53)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'Web Development', 'A', 85)''')
cursor.execute('''Insert Into STUDENT values('Jack', 'AI', 'B', 50)''')
cursor.execute('''Insert Into STUDENT values('Frank', 'Machine Learning', 'A', 73)''')
cursor.execute('''Insert Into STUDENT values('Shah', 'Machine Learning', 'C', 96)''')
cursor.execute('''Insert Into STUDENT values('Grace', 'DEVOPS', 'B', 87)''')
cursor.execute('''Insert Into STUDENT values('Alice', 'DEVOPS', 'F', 54)''')
cursor.execute('''Insert Into STUDENT values('Emily', 'DEVOPS', 'A', 72)''')
cursor.execute('''Insert Into STUDENT values('Bob', 'Machine Learning', 'F', 95)''')
cursor.execute('''Insert Into STUDENT values('Bibek', 'Data Analyst', 'D', 75)''')

#Display all the records
print('The inserted records are: ')

data = cursor.execute('''Select * From STUDENT''')

for row in data:
    print(row)

# close connection
connection.commit()
connection.close()